// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.cdz.netty.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cdz.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
