// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.cdz.netty.proto;

/**
 * Protobuf type {@code com.cdz.proto.StudentRequestList}
 */
public  final class StudentRequestList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cdz.proto.StudentRequestList)
    StudentRequestListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentRequestList.newBuilder() to construct.
  private StudentRequestList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentRequestList() {
    ageList_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new StudentRequestList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentRequestList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ageList_ = new java.util.ArrayList<StudentRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            ageList_.add(
                input.readMessage(StudentRequest.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ageList_ = java.util.Collections.unmodifiableList(ageList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return StudentProto.internal_static_com_cdz_proto_StudentRequestList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return StudentProto.internal_static_com_cdz_proto_StudentRequestList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StudentRequestList.class, Builder.class);
  }

  public static final int AGELIST_FIELD_NUMBER = 1;
  private java.util.List<StudentRequest> ageList_;
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  public java.util.List<StudentRequest> getAgeListList() {
    return ageList_;
  }
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  public java.util.List<? extends StudentRequestOrBuilder>
      getAgeListOrBuilderList() {
    return ageList_;
  }
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  public int getAgeListCount() {
    return ageList_.size();
  }
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  public StudentRequest getAgeList(int index) {
    return ageList_.get(index);
  }
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  public StudentRequestOrBuilder getAgeListOrBuilder(
      int index) {
    return ageList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ageList_.size(); i++) {
      output.writeMessage(1, ageList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ageList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ageList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StudentRequestList)) {
      return super.equals(obj);
    }
    StudentRequestList other = (StudentRequestList) obj;

    if (!getAgeListList()
        .equals(other.getAgeListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAgeListCount() > 0) {
      hash = (37 * hash) + AGELIST_FIELD_NUMBER;
      hash = (53 * hash) + getAgeListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StudentRequestList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentRequestList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentRequestList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentRequestList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentRequestList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentRequestList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentRequestList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StudentRequestList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StudentRequestList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StudentRequestList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StudentRequestList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StudentRequestList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StudentRequestList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cdz.proto.StudentRequestList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cdz.proto.StudentRequestList)
      StudentRequestListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentProto.internal_static_com_cdz_proto_StudentRequestList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentProto.internal_static_com_cdz_proto_StudentRequestList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StudentRequestList.class, Builder.class);
    }

    // Construct using com.cdz.netty.proto.StudentRequestList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAgeListFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (ageListBuilder_ == null) {
        ageList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ageListBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return StudentProto.internal_static_com_cdz_proto_StudentRequestList_descriptor;
    }

    @Override
    public StudentRequestList getDefaultInstanceForType() {
      return StudentRequestList.getDefaultInstance();
    }

    @Override
    public StudentRequestList build() {
      StudentRequestList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StudentRequestList buildPartial() {
      StudentRequestList result = new StudentRequestList(this);
      int from_bitField0_ = bitField0_;
      if (ageListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ageList_ = java.util.Collections.unmodifiableList(ageList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ageList_ = ageList_;
      } else {
        result.ageList_ = ageListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StudentRequestList) {
        return mergeFrom((StudentRequestList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StudentRequestList other) {
      if (other == StudentRequestList.getDefaultInstance()) return this;
      if (ageListBuilder_ == null) {
        if (!other.ageList_.isEmpty()) {
          if (ageList_.isEmpty()) {
            ageList_ = other.ageList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAgeListIsMutable();
            ageList_.addAll(other.ageList_);
          }
          onChanged();
        }
      } else {
        if (!other.ageList_.isEmpty()) {
          if (ageListBuilder_.isEmpty()) {
            ageListBuilder_.dispose();
            ageListBuilder_ = null;
            ageList_ = other.ageList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ageListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAgeListFieldBuilder() : null;
          } else {
            ageListBuilder_.addAllMessages(other.ageList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StudentRequestList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StudentRequestList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<StudentRequest> ageList_ =
      java.util.Collections.emptyList();
    private void ensureAgeListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ageList_ = new java.util.ArrayList<StudentRequest>(ageList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        StudentRequest, StudentRequest.Builder, StudentRequestOrBuilder> ageListBuilder_;

    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public java.util.List<StudentRequest> getAgeListList() {
      if (ageListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ageList_);
      } else {
        return ageListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public int getAgeListCount() {
      if (ageListBuilder_ == null) {
        return ageList_.size();
      } else {
        return ageListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public StudentRequest getAgeList(int index) {
      if (ageListBuilder_ == null) {
        return ageList_.get(index);
      } else {
        return ageListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder setAgeList(
        int index, StudentRequest value) {
      if (ageListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgeListIsMutable();
        ageList_.set(index, value);
        onChanged();
      } else {
        ageListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder setAgeList(
        int index, StudentRequest.Builder builderForValue) {
      if (ageListBuilder_ == null) {
        ensureAgeListIsMutable();
        ageList_.set(index, builderForValue.build());
        onChanged();
      } else {
        ageListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder addAgeList(StudentRequest value) {
      if (ageListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgeListIsMutable();
        ageList_.add(value);
        onChanged();
      } else {
        ageListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder addAgeList(
        int index, StudentRequest value) {
      if (ageListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgeListIsMutable();
        ageList_.add(index, value);
        onChanged();
      } else {
        ageListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder addAgeList(
        StudentRequest.Builder builderForValue) {
      if (ageListBuilder_ == null) {
        ensureAgeListIsMutable();
        ageList_.add(builderForValue.build());
        onChanged();
      } else {
        ageListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder addAgeList(
        int index, StudentRequest.Builder builderForValue) {
      if (ageListBuilder_ == null) {
        ensureAgeListIsMutable();
        ageList_.add(index, builderForValue.build());
        onChanged();
      } else {
        ageListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder addAllAgeList(
        Iterable<? extends StudentRequest> values) {
      if (ageListBuilder_ == null) {
        ensureAgeListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ageList_);
        onChanged();
      } else {
        ageListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder clearAgeList() {
      if (ageListBuilder_ == null) {
        ageList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ageListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public Builder removeAgeList(int index) {
      if (ageListBuilder_ == null) {
        ensureAgeListIsMutable();
        ageList_.remove(index);
        onChanged();
      } else {
        ageListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public StudentRequest.Builder getAgeListBuilder(
        int index) {
      return getAgeListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public StudentRequestOrBuilder getAgeListOrBuilder(
        int index) {
      if (ageListBuilder_ == null) {
        return ageList_.get(index);  } else {
        return ageListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public java.util.List<? extends StudentRequestOrBuilder>
         getAgeListOrBuilderList() {
      if (ageListBuilder_ != null) {
        return ageListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ageList_);
      }
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public StudentRequest.Builder addAgeListBuilder() {
      return getAgeListFieldBuilder().addBuilder(
          StudentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public StudentRequest.Builder addAgeListBuilder(
        int index) {
      return getAgeListFieldBuilder().addBuilder(
          index, StudentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
     */
    public java.util.List<StudentRequest.Builder>
         getAgeListBuilderList() {
      return getAgeListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        StudentRequest, StudentRequest.Builder, StudentRequestOrBuilder>
        getAgeListFieldBuilder() {
      if (ageListBuilder_ == null) {
        ageListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            StudentRequest, StudentRequest.Builder, StudentRequestOrBuilder>(
                ageList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ageList_ = null;
      }
      return ageListBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cdz.proto.StudentRequestList)
  }

  // @@protoc_insertion_point(class_scope:com.cdz.proto.StudentRequestList)
  private static final StudentRequestList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StudentRequestList();
  }

  public static StudentRequestList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentRequestList>
      PARSER = new com.google.protobuf.AbstractParser<StudentRequestList>() {
    @Override
    public StudentRequestList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentRequestList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentRequestList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StudentRequestList> getParserForType() {
    return PARSER;
  }

  @Override
  public StudentRequestList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

