// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.cdz.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cdz.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cdz.proto.StudentResponse studentList = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentListList();
  /**
   * <code>repeated .com.cdz.proto.StudentResponse studentList = 1;</code>
   */
  StudentResponse getStudentList(int index);
  /**
   * <code>repeated .com.cdz.proto.StudentResponse studentList = 1;</code>
   */
  int getStudentListCount();
  /**
   * <code>repeated .com.cdz.proto.StudentResponse studentList = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentListOrBuilderList();
  /**
   * <code>repeated .com.cdz.proto.StudentResponse studentList = 1;</code>
   */
  StudentResponseOrBuilder getStudentListOrBuilder(
          int index);
}
