// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.cdz.netty.proto;

public interface StudentRequestListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cdz.proto.StudentRequestList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  java.util.List<StudentRequest>
      getAgeListList();
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  StudentRequest getAgeList(int index);
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  int getAgeListCount();
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  java.util.List<? extends StudentRequestOrBuilder>
      getAgeListOrBuilderList();
  /**
   * <code>repeated .com.cdz.proto.StudentRequest ageList = 1;</code>
   */
  StudentRequestOrBuilder getAgeListOrBuilder(
          int index);
}
